site_name: Vinagent
site_url: https://github.com/datascienceworld-kan/vinagent-docs
theme:
  name: material
  palette:
      primary: indigo
      features:
        - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Usage: usage.md
  - API Reference: api.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
